baseurl = "https://info.wsouza.com.br"
languageCode = "en-us"
paginate = "9" # Number of posts per page
theme = "mainroad"
title = "Dicas Linux e Windows"
disqusShortname = "dicaslinuxewindows" # Enable comments by entering your Disqus shortname
googleAnalytics = "G-755N0HW50E" # Enable Google Analytics by entering your tracking id
enableEmoji = true
enableRobotsTXT = false
enableMissingTranslationPlaceholders = true

[menu]
  [[menu.main]]
    identifier = "home"
    name = "Home"
    url = "/"
    weight = 1
  [[menu.main]]
    identifier = "category"
    name = "Categorias"
    url = "#"
    weight = 2
  [[menu.main]]
    identifier = "category1"
    name = "Artigos"
    url = "/categories/artigos"
    parent = "category"
    weight = 1
  [[menu.main]]
    identifier = "category2"
    name = "Dicas"
    url = "/categories/dicas"
    parent = "category"
    weight = 2
    [[menu.main]]
    identifier = "category3"
    name = "Educacional"
    url = "/categories/educacional"
    parent = "category"
    weight = 3
    [[menu.main]]
    identifier = "category4"
    name = "Tutoriais"
    url = "/categories/tutoriais"
    parent = "category"
    weight = 4
    [[menu.main]]
    identifier = "system"
    name = "Sistemas"
    url = "#"
    weight = 3
  [[menu.main]]
    identifier = "system1"
    name = "Android"
    url = "/categories/android"
    parent = "system"
    weight = 1
  [[menu.main]]
    identifier = "system2"
    name = "Debian"
    url = "/categories/debian"
    parent = "system"
    weight = 2
    [[menu.main]]
    identifier = "system3"
    name = "Fedora"
    url = "/categories/fedora"
    parent = "system"
    weight = 3
    [[menu.main]]
    identifier = "system4"
    name = "Linux Mint"
    url = "/categories/linux-mint"
    parent = "system"
    weight = 4
    [[menu.main]]
    identifier = "system5"
    name = "Ubuntu"
    url = "/categories/ubuntu"
    parent = "system"
    weight = 5
    [[menu.main]]
    identifier = "system6"
    name = "Windows"
    url = "/categories/windows"
    parent = "system"
    weight = 6
  [[menu.main]]
    identifier = "about"
    name = "Sobre"
    url = "/sobre/"
    weight = 4

 [Author]
  name = "W.Souza"
  bio = "Usuário de Debian e Windows. Gosto de compartilhar as experiências e dificuldades encontradas no dia-a-dia."
  avatar = "https://blogger.googleusercontent.com/img/a/AVvXsEhaExMFQx736MAebmuSzIyJaP4wXZqkvKAhf5qwME44A31K4kwqWj0dqCDisf-Jh9QQiwZmVPandEty4NfHQIZ2nS-kucDGBk4nMR7RGeklzk4NwEseZmNQ97hjQmo1kNdUGQyAhdNb5piMf4F05_fMsnr8dOu-XN7xNy-hig6tiswpp5sNANkGkvArkw"

[Params]
  description = "Dicas, tutoriais e algumas curiosidades sobre Internet, Sistemas Operacionais Windows, Linux e Mobile." # Description of your site
  opengraph = true
  copyright = "Dicas Linux e Windows | Ao compartilhar, cite a fonte "
  schema = true # Enable Schema
  twitter_cards = true # Enable Twitter Cards if true
  toc = true # Enable Table of Contents
  readmore = true # Show "Read more" button in list if true
  authorbox = true
  pager = true
  keyword = "Windows, Linux, Mobile, Internet, Android, Dicas, Artigos, Tutoriais"
  post_meta = ["author", "date", "categories", "translations"]
  googleAnalyticsID = "G-755N0HW50E"
  show_translations= true
  dateFormat = "Mon, Jan 2, 2006"
  enableGitInfo = true
  favicon32 = "/favicon-32x32.png"
  favicon16 = "/favicon.ico"

[markup]
[markup.goldmark]
[markup.goldmark.renderer]
 unsafe = true

[Params.thumbnail]
  visibility = ["list", "post"] # Control thumbnail visibility
  
[Params.logo]
  image = "https://blogger.googleusercontent.com/img/a/AVvXsEiIl2noRmnGVLZlSyL10HlZDojXtx7ECMx8OCId7hsJSTD-cT_aXWybB5NA6aGORF3m5KhsbejbMrKItUa-EMTL3-aKBLAXiW7MzliqqR_hX5uR0cjp15F8-8JGF8oieC0shsU2Ic-Zz0Q3JEbHNJMBH3PytR8G6LLL4OPqVr1XWnlXMXh6N0wbe9aang"
  subtitle = "" # Logo subtitle

[Params.sidebar]
  home = "right"   # Configure layout for home page
  list = "right"   # Configure layout for list pages
  single = "true" # Configure layout for single pages
  widgets = ["languages", "search", "recent", "taglist", "social"]

[Params.widgets]
  recent_num = 5 # Set the number of articles in the "Recent articles" widget
  tags_counter = true # Enable counter for each tag in "Tags" widget (disabled by default)
  
[Params.widgets.social]
  # Enable parts of social widget
  twitter = "dicaslnxwindows"
  github = "andradeswagner"
  email = "dicaslinuxewindows@gmail.com"
  rss = "https://info.wsouza.com.br/sitemap.xml"
  
[[Params.widgets.social.custom]]
  title = "Youtube"
  url = "https://youtube.com/channel/UCdgAIchdOo7lsyKge8m-P_w"
  icon = "svg/youtube3.svg" 
